export interface FAQItem {
  id: string;
  group: 'global' | 'local';
  label: string;
  keywords: string[];
  question: string;
  answer: string;
}

export const faqMap: FAQItem[] = [
  {
    id: 'what-is-hekahub',
    group: 'global',
    label: 'About HekaHub',
    keywords: [
      // Direct name queries
      'what is hekahub',
      'what is heka hub',
      'hekahub',
      'heka hub',
      'about hekahub',
      'about heka hub',
      'hekahub meaning',
      'what does hekahub mean',
      'what does heka mean',
      'heka meaning',

      // Identity / who are you
      'who are you',
      'who is this',
      'who made this',
      'who built this',
      'who created hekahub',
      'what are you',
      'tell me about yourself',
      'tell me about hekahub',
      'explain hekahub',
      'describe hekahub',
      'what do you do',
      'what does hekahub do',
      'what does hekahub offer',
      'what is this platform',
      'what is this website',
      'what is this app',

      // Purpose / mission
      'what is hekahub about',
      'what is the purpose of hekahub',
      'hekahub mission',
      'hekahub vision',
      'hekahub goal',
      'what does hekahub teach',
      'what can i learn on hekahub',
      'is hekahub an ai school',
      'is hekahub a coding school',
      'is hekahub a learning platform',
      'is this an edtech platform',
      'edtech for kids',
      'ai learning for kids',
      'ai school for kids',
      'ai education platform',
      'learning platform for kids',

      // Audience curiosity
      'who is hekahub for',
      'is hekahub for me',
      'is this for students',
      'is this for children',
      'is this for teens',

      // Typos / alternate spellings
      'hekahub',
      'heka-hub',
      'hekah ub',
      'heka hb',
    ],
    question: 'What is HekaHub?',
    answer:
      'HekaHub is an AI-powered learning ecosystem designed specifically for the next generation of innovators (ages 10-15). We bridge the gap between curiosity and creation, teaching kids not just how to use AI, but how to build with it.',
  },

  {
    id: 'summer-bootcamp',
    group: 'global',
    label: 'Summer Bootcamp',
    keywords: [
      // Core terms
      'summer bootcamp',
      'bootcamp',
      'boot camp',
      'summer boot camp',
      'summer program',
      'summer course',
      'summer class',
      'summer training',
      'summer camp',
      'ai summer camp',
      'coding summer camp',
      'ai bootcamp',
      'coding bootcamp',
      'tech bootcamp',

      // Duration related
      '8 weeks',
      'eight weeks',
      '8 week program',
      '8-week',
      '8 week course',
      'how long is bootcamp',
      'how long is the program',
      'how many weeks',
      'duration of bootcamp',

      // Content related
      'intensive program',
      'intensive course',
      'immersive program',
      '160 hours',
      '40 classes',
      'how many classes',
      'how many sessions',
      'what happens in bootcamp',
      'what is included in bootcamp',
      'what do you learn in bootcamp',
      'what will my child learn',
      'bootcamp curriculum',
      'bootcamp syllabus',
      'bootcamp schedule',
      'bootcamp content',

      // Registration / interest
      'tell me about the bootcamp',
      'tell me about summer bootcamp',
      'summer bootcamp details',
      'bootcamp details',
      'join bootcamp',
      'enroll in bootcamp',
      'sign up for bootcamp',
      'register for bootcamp',
      'how to join bootcamp',
      'how to enroll',
      'bootcamp enrollment',
      'bootcamp registration',
      'is bootcamp open',
      'when does bootcamp start',
      'bootcamp start date',
      'bootcamp dates',
      'when is bootcamp',

      // Reward / outcome
      'bootcamp reward',
      'bootcamp completion',
      'what do you get after bootcamp',
      'bootcamp kit',
      'completion kit',
      'reward kit',
    ],
    question: 'Tell me about the Summer Bootcamp.',
    answer:
      'The Summer Bootcamp is an intensive **8-week** AI deep-dive:\n\n• **160+ hours** of immersive learning\n• **40 classes**, each 4 hours long\n• Revision classes + weekly newsletter\n• Physical **completion reward kit** + certificate\n• Free trial classes available on request\n\n**Price:** $600 Early Bird *(was $1,999)* · or pay $25/class, $100/week, $350/month. Registration fee: $99.',
  },

  {
    id: 'pricing-plans',
    group: 'global',
    label: 'Pricing & Plans',
    keywords: [
      // Core pricing
      'pricing',
      'price',
      'prices',
      'cost',
      'costs',
      'how much',
      'how much does it cost',
      'how much is it',
      'how much does hekahub cost',
      'what is the cost',
      'what is the price',
      'fees',
      'fee',
      'tuition',
      'charges',

      // Plans
      'plans',
      'plan',
      'membership',
      'memberships',
      'subscription',
      'subscriptions',
      'packages',
      'package',
      'options',
      'tiers',
      'what plans are available',
      'what packages do you offer',
      'what are the plans',
      'annual membership',
      'annual plan',
      'yearly plan',
      'monthly plan',

      // Early bird / discounts
      'early bird',
      'early bird discount',
      'discount',
      'discounts',
      'promo',
      'promo code',
      'coupon',
      'offer',
      'sale',
      'deal',
      'special offer',
      'reduced price',
      'cheaper option',
      'affordable',
      'is it affordable',

      // Per class / per session
      'per class',
      'per session',
      'class price',
      'session price',
      'how much per class',
      'individual class',
      'single class',
      'pay per class',

      // Batch types
      'weekday batch',
      'weekend batch',
      'weekday class',
      'weekend class',
      'batch options',
      'which batch',
      'weekday or weekend',

      // Bootcamp pricing specifically
      'bootcamp cost',
      'bootcamp price',
      'how much is the bootcamp',
      'bootcamp fee',
      'bootcamp pricing',
      '$600',
      '600 dollars',

      // Payment
      'payment',
      'payment options',
      'how to pay',
      'payment methods',
      'can i pay monthly',
      'installment',
      'emi',
      'refund',
      'refund policy',
      'money back',
    ],
    question: 'What are the pricing plans?',
    answer:
      'We have 4 plans — all include a certificate, reward kit, revision classes & weekly newsletter:\n\n• **Summer Bootcamp** — $25/class · $100/week · $350/month · **$600/bootcamp** *(Early Bird, was $1,999)*\n• **Weekday Batch** — $59.99/month *(52 weeks, 240 classes × 45 min)*\n• **Weekend Batch** — $59.99/month *(52 weeks, 80 classes × 2 hrs)*\n• **Annual Membership** — **$1,100/year** *(Early Bird, was $4,999)* — all bootcamps + 320+ hrs + guest sessions + welcome gift\n\nAll plans have a $99 registration fee. Group/school bookings? [Let\'s talk!]',
  },

  {
    id: 'age-group',
    group: 'local',
    label: 'Age Group',
    keywords: [
      // Direct age queries
      'age',
      'ages',
      'age group',
      'age range',
      'age limit',
      'what age',
      'how old',
      'how old do you have to be',
      'minimum age',
      'maximum age',
      'what age can join',
      'what age is it for',
      'is there an age limit',
      'years old',
      '10 years old',
      '11 years old',
      '12 years old',
      '13 years old',
      '14 years old',
      '15 years old',
      '10 to 15',
      '10-15',
      'ages 10 to 15',
      'ages 10-15',

      // Audience descriptors
      'kids',
      'children',
      'child',
      'teens',
      'teen',
      'teenager',
      'teenagers',
      'tweens',
      'tween',
      'young learners',
      'youth',
      'juniors',
      'school kids',
      'school children',
      'middle school',
      'middle schoolers',
      'grade school',

      // Parent perspective
      'is it for my child',
      'is it for my kid',
      'can my child join',
      'can my 10 year old join',
      'can my 11 year old join',
      'can my 12 year old join',
      'can my 13 year old join',
      'can my 14 year old join',
      'can my 15 year old join',
      'is my child old enough',
      'target audience',
      'who is this for',
      'who is hekahub for',
      'is this for kids',
      'is this for teens',
      'suitable age',
      'appropriate age',

      // Older / younger edge cases
      'can adults join',
      'is it only for kids',
      'can someone older join',
      'what if my child is younger',
      'what if my child is older',
      'above 15',
      'below 10',
      'under 10',
      'over 15',
    ],
    question: 'What age group is HekaHub for?',
    answer:
      'HekaHub is primary designed for students aged **10 to 15 years old**. Our curriculum is structured to be challenging yet accessible for this developmental stage.',
  },

  {
    id: 'prerequisites',
    group: 'local',
    label: 'Prerequisites',
    keywords: [
      // Direct prerequisite queries
      'prerequisites',
      'prerequisite',
      'requirements',
      'requirement',
      'do i need coding',
      'do i need to know coding',
      'do i need prior experience',
      'prior experience',
      'prior knowledge',
      'background',
      'background required',
      'coding background',
      'tech background',
      'level',
      'skill level',
      'what level',
      'experience level',

      // Beginner questions
      'beginner',
      'beginners',
      'complete beginner',
      'total beginner',
      'zero experience',
      'no experience',
      'no coding experience',
      'no prior coding',
      'no background',
      'is it for beginners',
      'can a beginner join',
      'i have no coding experience',
      'my child has no experience',
      'first time learner',
      'new to coding',
      'new to programming',
      'new to ai',
      'never coded before',
      'never programmed before',
      'from scratch',
      'starting from zero',
      'starting from scratch',

      // Coding / programming specific
      'do i need to know programming',
      'do i need to know python',
      'programming experience',
      'python experience',
      'coding skills',
      'coding knowledge',
      'is coding required',
      'is programming required',

      // Equipment / setup
      'what do i need',
      'what equipment do i need',
      'laptop',
      'do i need a laptop',
      'computer',
      'do i need a computer',
      'device',
      'what device',
      'internet',
      'internet connection',
      'wifi',
      'stable internet',
      'do i need wifi',
      'technical requirements',
      'setup requirements',
      'system requirements',

      // Readiness / eligibility
      'am i eligible',
      'can i join',
      'is my child eligible',
      'can my child join',
      'is hekahub suitable for beginners',
      'will my child cope',
      'is it too hard',
      'is it difficult',
      'how hard is it',
      'difficulty level',
      'is it easy',
    ],
    question: 'Do I need prior coding experience or is there a any prerequisites?',
    answer:
      'No prior coding experience is required! We start from first principles. All you need is a laptop, a stable internet connection, and a curious mind.',
  },

  {
    id: 'certificates',
    group: 'local',
    label: 'Certificates',
    keywords: [
      // Certificate / certification
      'certificate',
      'certificates',
      'certification',
      'certifications',
      'certified',
      'do i get a certificate',
      'will i get a certificate',
      'is there a certificate',
      'completion certificate',
      'course certificate',
      'program certificate',
      'hekahub certificate',

      // Diploma / credential
      'diploma',
      'degree',
      'credential',
      'credentials',
      'accreditation',
      'accredited',
      'is it accredited',
      'recognized certificate',
      'official certificate',

      // Proof of completion
      'proof of completion',
      'completion',
      'completed',
      'course completion',
      'bootcamp completion',
      'what happens after i complete',
      'after finishing the course',
      'after completing bootcamp',
      'end of program',
      'end of course',

      // Reward / physical kit
      'reward',
      'rewards',
      'reward kit',
      'completion kit',
      'kit',
      'physical reward',
      'physical kit',
      'what do i get',
      'what do i receive',
      'what do graduates get',
      'bootcamp graduates',
      'graduation',
      'do i graduate',
      'graduate',

      // Value of certificate
      'is the certificate useful',
      'is the certificate recognized',
      'certificate value',
      'will it help my resume',
      'resume',
      'portfolio',
      'badge',
      'digital badge',
      'linkedin certificate',
      'add to linkedin',
    ],
    question: 'Do I get a certificate?',
    answer:
      'Yes! Upon successful completion of our programs, students receive a **HekaHub Certificate of Completion**, along with a physical reward kit for our bootcamp graduates.',
  },

  // ─── PRICING DEEP-DIVES ───────────────────────────────────────────────────

  {
    id: 'annual-membership',
    group: 'global',
    label: 'Annual Membership',
    keywords: [
      'annual membership', 'annual plan', 'yearly plan', 'yearly membership',
      'full year', 'all year', 'year long', '1 year', 'one year',
      'annual price', 'annual cost', 'how much is annual', 'annual fee',
      '1100', '$1100', '1100 dollars', 'annual early bird',
      'all bootcamps', 'all seasons', 'every bootcamp',
      '320 hours', '320+ hours',
      'crash course library', 'library access', 'course library',
      'guest sessions', 'guest expert', 'live sessions', 'expert sessions',
      'infographics', 'ai infographics', 'brain first',
      'welcome gift', 'enrollment gift', 'welcome kit',
      'best plan', 'most value', 'best value plan', 'recommended plan',
      'is annual worth it', 'should i get annual',
    ],
    question: 'What does the Annual Membership include?',
    answer:
      '**Annual Membership** — the all-in plan for learners who never stop:\n\n• All seasonal bootcamps included\n• **320+ hours** of AI learning\n• Crash Course Library access\n• Live guest expert sessions\n• Brain-first AI infographics\n• Revision classes + weekly newsletter\n• Certificate + completion reward kit\n• Exclusive welcome enrollment gift\n\n**Price:** $1,100/year *(Early Bird, was $4,999)* + $99 registration fee.',
  },

  {
    id: 'weekday-batch',
    group: 'global',
    label: 'Weekday Batch',
    keywords: [
      'weekday batch', 'weekday plan', 'weekday classes', 'weekday schedule',
      'school days', 'monday to friday', 'mon to fri', 'weekdays only',
      'weekday program', 'weekday sessions',
      'how many weekday classes', 'weekday class duration', '45 minutes', '45 min class',
      '240 classes', '52 weeks weekday',
      '$59.99', '59.99', '59 per month', 'monthly weekday',
      'is weekday right for me', 'weekday vs weekend',
      'fits school schedule', 'school schedule plan',
    ],
    question: 'What is the Weekday Batch?',
    answer:
      "The **Weekday Batch** fits around your child's school routine:\n\n• **52 weeks** of AI learning\n• **240 classes**, each 45 minutes\n• 160+ hours of immersive content\n• Revision classes + weekly newsletter\n• Certificate + completion reward kit\n• Free trial classes on request\n\n**Price:** $59.99/month + $99 registration fee.",
  },

  {
    id: 'weekend-batch',
    group: 'global',
    label: 'Weekend Batch',
    keywords: [
      'weekend batch', 'weekend plan', 'weekend classes', 'weekend schedule',
      'saturday sunday', 'saturday class', 'sunday class', 'weekends only',
      'weekend program', 'weekend sessions', 'weekend learning',
      'how many weekend classes', 'weekend class duration', '2 hours', '2 hour class',
      '80 classes', '52 weeks weekend',
      'deep dive weekend', 'intensive weekend',
      'is weekend right for me', 'weekday vs weekend',
      '$59.99 weekend', '59.99 weekend', 'monthly weekend',
    ],
    question: 'What is the Weekend Batch?',
    answer:
      'The **Weekend Batch** is for deep-dive learners:\n\n• **52 weeks** of AI learning\n• **80 classes**, each 2 hours long\n• 160+ hours of immersive content\n• Revision classes + weekly newsletter\n• Certificate + completion reward kit\n• Free trial classes on request\n\n**Price:** $59.99/month + $99 registration fee.',
  },

  {
    id: 'registration-fee',
    group: 'global',
    label: 'Registration Fee',
    keywords: [
      'registration fee', 'registration cost', 'registration charge',
      'signup fee', 'sign up fee', 'joining fee', 'onboarding fee',
      '$99', '99 dollars', '99 fee',
      'is there a registration fee', 'do i pay a registration fee',
      'what is the registration fee', 'why is there a registration fee',
      'additional fee', 'extra fee', 'hidden fee', 'hidden cost',
      'total cost', 'total price', 'all in cost',
    ],
    question: 'Is there a registration fee?',
    answer:
      'Yes — all plans have a one-time **$99 registration fee** on top of the plan price. This covers your onboarding, account setup, and welcome materials.',
  },

  {
    id: 'free-trial',
    group: 'global',
    label: 'Free Trial',
    keywords: [
      'free trial', 'trial class', 'free class', 'demo class', 'sample class',
      'try before buying', 'can i try first', 'free session', 'trial session',
      'is there a free trial', 'do you offer a trial',
      'test the class', 'try a class', 'first class free',
      'before enrolling', 'before i enroll', 'before signing up',
    ],
    question: 'Can I try a class before enrolling?',
    answer:
      "Yes! Free trial classes are available **upon request** for all plans. Just reach out and we'll set one up for your child before you commit.",
  },

  {
    id: 'group-booking',
    group: 'global',
    label: 'Group / School Bookings',
    keywords: [
      'group booking', 'group plan', 'school booking', 'school plan',
      'organisation', 'organization', 'cohort', 'bulk booking',
      'bulk enrollment', 'team enrollment', 'multiple students',
      'school program', 'school partnership', 'institutional plan',
      'custom plan', 'custom pricing', 'bespoke plan',
      'corporate', 'nonprofit', 'ngo',
      'can a school join', 'can my school enroll', 'school discount',
      'group discount', 'bulk discount',
      "let's talk", 'contact for pricing',
    ],
    question: 'Do you have plans for schools or groups?',
    answer:
      "Absolutely! We offer **custom plans for schools, organisations, and cohorts**. Pricing and structure are tailored to your group size and needs. Reach out via the \"Let's Talk\" option and we'll build something together.",
  },

  // ─── CURRICULUM DEEP-DIVES ────────────────────────────────────────────────

  {
    id: 'curriculum-overview',
    group: 'global',
    label: 'Curriculum Overview',
    keywords: [
      'curriculum', 'syllabus', 'course content', 'what will i learn',
      'what do you teach', 'topics covered', 'subjects', 'modules',
      'course outline', 'lesson plan', 'learning plan',
      'what is taught', 'what is in the course',
      'weekly topics', 'week by week', 'what happens each week',
      'all weeks', 'full curriculum', 'full syllabus',
      'overview of course', 'course structure',
      'prompt engineering', 'sentiment analysis', 'memory', 'structured output',
      'classification', 'storytelling ai', 'ai creativity', 'ai portfolio',
      'founder mindset', 'capstone project',
    ],
    question: 'What does the curriculum cover?',
    answer:
      'The 8-week curriculum builds from fundamentals to a full founder-level project:\n\n• **Wk 1 — Talk to AI:** Prompt engineering & dynamic prompts\n• **Wk 2 — AI Feels the Vibe:** Sentiment analysis & tone classification\n• **Wk 3 — AI Remembers You:** System prompts, memory & stateful chat\n• **Wk 4 — The Brain Organiser:** Structured output, JSON & conditional logic\n• **Wk 5 — Lie Detector Mode:** Classification & chain-of-thought reasoning\n• **Wk 6 — Born to Storytell:** Creative generation & multimodal output\n• **Wk 7 — Your Story, Your Stage:** AI-generated bio, resume & publishing\n• **Wk 8 — Think Like Founders:** Problem framing → pitch → full AI product',
  },

  // {
  //   id: 'week1',
  //   group: 'local',
  //   label: 'Week 1 – Prompt Engineering',
  //   keywords: [
  //     'week 1', 'week one', 'first week', 'wk1',
  //     'talk to ai', 'talking to ai',
  //     'prompt engineering', 'prompting', 'how to prompt',
  //     'input output', 'how ai works', 'what is a prompt',
  //     'dynamic prompts', 'prompt basics', 'writing prompts',
  //   ],
  //   question: 'What is covered in Week 1?',
  //   answer:
  //     "**Week 1 — Talk to AI:** You're the author; AI is your pen.\n\n• Prompt Engineering — crafting inputs that guide AI reliably\n• Input → Output loop — the foundation of every AI interaction\n• Dynamic Prompts — prompts that change based on user input",
  // },

  // {
  //   id: 'week2',
  //   group: 'local',
  //   label: 'Week 2 – Sentiment Analysis',
  //   keywords: [
  //     'week 2', 'week two', 'second week', 'wk2',
  //     'ai feels the vibe', 'sentiment', 'vibe',
  //     'sentiment analysis', 'emotion detection', 'mood detection',
  //     'tone classification', 'tone detection', 'tone analysis',
  //     'conditional rewriting', 'text rewriting', 'emotion ai',
  //   ],
  //   question: 'What is covered in Week 2?',
  //   answer:
  //     '**Week 2 — AI Feels the Vibe:** Words carry emotion — AI can read it.\n\n• Sentiment Analysis — detecting positive, negative, or neutral emotion\n• Tone Classification — identifying formal, sarcastic, or warm register\n• Conditional Rewriting — shifting tone while preserving meaning',
  // },

  // {
  //   id: 'week3',
  //   group: 'local',
  //   label: 'Week 3 – AI Memory & Personas',
  //   keywords: [
  //     'week 3', 'week three', 'third week', 'wk3',
  //     'ai remembers you', 'ai memory', 'memory',
  //     'system prompts', 'system prompt', 'persona', 'ai persona',
  //     'conversation context', 'context window', 'chat history',
  //     'stateful chat', 'stateful', 'chatbot memory',
  //     'how does ai remember', 'how to give ai a personality',
  //   ],
  //   question: 'What is covered in Week 3?',
  //   answer:
  //     "**Week 3 — AI Remembers You:** Teach AI to hold a personality.\n\n• System Prompts — hidden instructions that set AI's persona & rules\n• Conversation Context — passing prior messages so AI can reference them\n• Stateful Chat — building responses that build on what came before",
  // },

  // {
  //   id: 'week4',
  //   group: 'local',
  //   label: 'Week 4 – Structured Output',
  //   keywords: [
  //     'week 4', 'week four', 'fourth week', 'wk4',
  //     'brain organiser', 'brain organizer', 'organiser',
  //     'structured output', 'json', 'json parsing', 'tables', 'lists',
  //     'conditional logic', 'conditional inputs', 'structured data',
  //     'ai organises', 'ai organizer', 'data structure',
  //   ],
  //   question: 'What is covered in Week 4?',
  //   answer:
  //     "**Week 4 — The Brain Organiser:** Chaos → clarity.\n\n• Structured Output — prompting AI to return JSON, tables, or numbered lists\n• JSON Parsing — displaying AI-generated data inside an app's UI\n• Conditional Logic — using inputs to shape what AI produces",
  // },

  // {
  //   id: 'week5',
  //   group: 'local',
  //   label: 'Week 5 – Classification',
  //   keywords: [
  //     'week 5', 'week five', 'fifth week', 'wk5',
  //     'lie detector', 'lie detector mode', 'fake news', 'real or fake',
  //     'classification', 'classify', 'ai classify',
  //     'confidence scoring', 'confidence score', 'probability',
  //     'chain of thought', 'chain-of-thought', 'reasoning', 'step by step reasoning',
  //     'spam detection', 'fact check', 'ai fact checking',
  //   ],
  //   question: 'What is covered in Week 5?',
  //   answer:
  //     '**Week 5 — Lie Detector Mode:** Train AI to judge, classify & explain.\n\n• Classification — AI assigning inputs to categories (real/fake, safe/spam)\n• Confidence Scoring — AI expressing certainty as a percentage\n• Chain-of-Thought — prompting AI to reason step by step before answering',
  // },

  // {
  //   id: 'week6',
  //   group: 'local',
  //   label: 'Week 6 – Creative Storytelling',
  //   keywords: [
  //     'week 6', 'week six', 'sixth week', 'wk6',
  //     'born to storytell', 'storytelling', 'story', 'creative writing',
  //     'creative generation', 'ai storytelling', 'ai stories', 'ai writing',
  //     'style conditioning', 'genre', 'tone genre', 'narrative',
  //     'multimodal output', 'image generation', 'text and images',
  //     'ai co-author', 'ai author', 'creative ai',
  //   ],
  //   question: 'What is covered in Week 6?',
  //   answer:
  //     '**Week 6 — Born to Storytell:** AI becomes your co-author.\n\n• Creative Generation — prompting AI to produce original narratives\n• Style Conditioning — steering output by genre or tone parameters\n• Multimodal Output — combining text + image generation for richer media',
  // },

  // {
  //   id: 'week7',
  //   group: 'local',
  //   label: 'Week 7 – AI Portfolio & Publishing',
  //   keywords: [
  //     'week 7', 'week seven', 'seventh week', 'wk7',
  //     'your story your stage', 'portfolio', 'personal portfolio',
  //     'bio', 'resume', 'ai resume', 'ai bio', 'ai generated resume',
  //     'persona generation', 'professional identity', 'personal brand',
  //     'multi format output', 'multiple formats', 'repurpose content',
  //     'publishing', 'deploy', 'share online', 'go live', 'publish to web',
  //   ],
  //   question: 'What is covered in Week 7?',
  //   answer:
  //     '**Week 7 — Your Story, Your Stage:** Let AI say it beautifully.\n\n• Persona Generation — using personal data to craft a professional identity\n• Multi-format Output — same content repurposed into bio, resume, fun facts\n• Publishing & Sharing — deploying AI-generated content live to the web',
  // },

  // {
  //   id: 'week8',
  //   group: 'local',
  //   label: 'Week 8 – Capstone / Founder Project',
  //   keywords: [
  //     'week 8', 'week eight', 'eighth week', 'wk8', 'last week', 'final week',
  //     'think like founders', 'founder', 'startup', 'capstone',
  //     'capstone project', 'final project', 'end project',
  //     'problem framing', 'pitch', 'business idea', 'ai product',
  //     'structured idea', 'idea generation', 'end to end', 'end-to-end workflow',
  //     'real world project', 'build something', 'launch project',
  //     'what is the final project', 'what do you build at the end',
  //   ],
  //   question: 'What is covered in Week 8?',
  //   answer:
  //     '**Week 8 — Think Like Founders:** Notice a problem. Build the pitch.\n\n• Problem Framing — real observations become the seed for AI-structured business ideas\n• Structured Idea Gen — AI produces name, model & risks from a single open-ended input\n• End-to-End Workflow — combining prompting, structured output & polished UI from all prior weeks\n\nThis is the capstone — students leave with a real AI product they built themselves.',
  // },
];